version: "3.3"

services:
  # mysql_db:
  #   platform: linux/x86_64 #error solved when using m1
  #   image: mysql:latest
  #   restart: always
  #   networks:
  #     - app-tier
  #   volumes:
  #     - ./mysql/db:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   cap_add:
  #     - SYS_NICE
  #   environment:
  #     - MYSQL_DATABASE=app
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=1234
  #     - MYSQL_ROOT_PASSWORD=1234
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    # command: python manage.py runserver 127.0.0.1:8000
    networks:
      - app-tier
    restart: always
    volumes:
      - ./backend/app:/app
    env_file:
      - ./backend/.env.dev

  migration:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # image: app
    command: sh -c "python3 manage.py migrate"
    volumes:
      - ./backend/app:/app
    # links:
    #     - mysql_db
    depends_on:
      - make_migrations

  make_migrations:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    # image: app
    command: sh -c "python3 manage.py makemigrations"
    volumes:
      - ./backend/app:/app

networks:
  app-tier:
    driver: bridge
